version: '3.8'

services:
  market-pulse:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped